### ISSUE TITLE
static.yml Bug Report

### ISSUE THREAD

**Issue by hasanraiyan** [hasanraiyan/TikTakToe#1]
I don't see any major bugs in the code you provided. However, there is a minor issue related to the `id-token: write` permission. GitHub Actions' `GITHUB_TOKEN` does not support the `id-token: write` permission, as it is not a valid permission scope. Here's the corrected `permissions` section:

```yaml
permissions:
  contents: read
  pages: write
```

Additionally, you may want to consider adding a `if: github.ref == 'refs/heads/main'` condition to the `Deploy to GitHub Pages` step to ensure that the deployment only happens when the main branch is targeted. Here's the updated `deploy` job with this condition:

```yaml
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        if: github.ref == 'refs/heads/main'
```

These changes will ensure that the workflow functions correctly and securely.
