### ISSUE TITLE
static.yml Bug Report

### ISSUE THREAD

**Issue by hasanraiyan** [hasanraiyan/TikTakToe#2]
I don't see any major bugs in the code you provided. However, there is a minor issue related to the `id-token: write` permission. GitHub Actions' `GITHUB_TOKEN` does not support the `id-token: write` permission, as it is not a valid permission scope. Here's the corrected `permissions` section:

```yaml
permissions:
  contents: read
  pages: write
```

Additionally, I would recommend adding a `jobs.<job_id>.steps.env` section to set the `GITHUB_REF` and `GITHUB_SHA` environment variables explicitly. This is not a bug, but it is a good practice to ensure these variables are available in the workflow. Here's the updated `deploy` job with the environment variables:

```yaml
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        env:
          GITHUB_REF: ${{ github.ref }}
          GITHUB_SHA: ${{ github.sha }}
```

With these changes, the workflow should function correctly and follow best practices.
